{"name": "test_negative_calorie_count", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: If dietry-fiber is greater than carbs then calorie count comes negative which is not as expected\nassert -15 == 265.0", "trace": "self = <test_cases.test_calorie_count.Test_001 object at 0x000001B7E719C4C0>\n\n    @pytest.mark.xfail\n    def test_negative_calorie_count(self):\n        file = self.test_calorie_sheet()\n        df = pd.read_excel(file)\n        print(df)\n        print(df.iloc[2].tolist())  # Get the third Row from excel using Pandas as a List\n        protein, carbs, dietry_fiber, fat, alcohol, expected = df.iloc[2].tolist()\n        total_calories = Test_001.calculate_calories(protein, carbs, dietry_fiber, fat, alcohol)\n        print(f'total_calories is {total_calories}')\n>       assert total_calories == expected, \"If dietry-fiber is greater than carbs then calorie count comes negative which is not as expected\"\nE       AssertionError: If dietry-fiber is greater than carbs then calorie count comes negative which is not as expected\nE       assert -15 == 265.0\n\ntest_calorie_count.py:63: AssertionError"}, "start": 1695922297267, "stop": 1695922297284, "uuid": "05d2675b-5740-4514-a1cf-4ef9769a729f", "historyId": "41f6076f4e077c6a1d7d00b65c40ccfc", "testCaseId": "41f6076f4e077c6a1d7d00b65c40ccfc", "fullName": "test_calorie_count.Test_001#test_negative_calorie_count", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_calorie_count"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "Priya-Lenovo"}, {"name": "thread", "value": "13476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calorie_count"}]}